#!/usr/bin/env python3
############################################################
# FlatCAM: 2D Post-processing for Manufacturing            #
############################################################

import sys
from PySide6 import QtGui, QtWidgets
from PySide6 import QtCore
from FlatCAMApp import App


# All X11 calling should be thread safe otherwise we have strange issues
# QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_X11InitThreads)
# NOTE: Never talk to the GUI from threads! This is why I commented the above.

app = QtWidgets.QApplication(sys.argv)
QtCore.QDir.setSearchPaths(
    "share",
    ["share", "share/flatcam", "/usr/share/flatcam"],
)
fc = App()
sys.exit(app.exec())
