############################################################
# FlatCAM: 2D Post-processing for Manufacturing            #
# A setuptools based setup module                          #
############################################################

from setuptools import setup
import glob

setup(
    name='FlatCAM',
    version='1.0',
    description='2D Computer-Aided PCB Manufacturing',
    long_description=(
        'FlatCAM is a program for preparing CNC jobs for making '
        'PCBs on a CNC router. Among other things, it can take '
        'a Gerber file generated by your favorite PCB CAD '
        'program, and create G-Code for Isolation routing.'
    ),
    url='https://bitbucket.org/jpcgt/flatcam',
    python_requires='>=3.10',
    packages=[
        'descartes',
        'tclCommands',
    ],
    py_modules=[
        'camlib',
        'FlatCAMApp',
        'FlatCAMCommon',
        'FlatCAMDraw',
        'FlatCAMGUI',
        'FlatCAMObj',
        'FlatCAMProcess',
        'FlatCAMShell',
        'FlatCAMTool',
        'FlatCAMVersion',
        'FlatCAMWorker',
        'GUIElements',
        'ObjectCollection',
        'ObjectUI',
        'PlotCanvas',
        'svgparse',
        'termwidget',
        'ToolDblSided',
        'ToolMeasurement',
        'ToolTransform',
    ],
    install_requires=[
        'PySide6>=6.6',
        'simplejson>=3.19',
        'numpy>=1.26',
        'scipy>=1.11',
        'matplotlib>=3.8',
        'shapely>=2.0',
        'rtree>=1.1',
        'svg.path>=6.3',
    ],
    extras_require={
        'windows': ['pywin32>=306'],
    },
    include_package_data=True,
    data_files=[
        ('share/flatcam', glob.glob('share/*')),
    ],
    scripts=['flatcam'],
)
